// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxl7baQenH7oFKaDXrzAaYFDCREni7B9Q',
    appId: '1:65493231963:android:ca7ca2df87fc755b7dd27e',
    messagingSenderId: '65493231963',
    projectId: 'oxyguard-f9e01',
    storageBucket: 'oxyguard-f9e01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkhIIcLHRiTLqL_lFvyea2v_mWFpapak',
    appId: '1:65493231963:ios:f9ade5aea727e62d7dd27e',
    messagingSenderId: '65493231963',
    projectId: 'oxyguard-f9e01',
    storageBucket: 'oxyguard-f9e01.appspot.com',
    iosBundleId: 'com.example.oxyGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkhIIcLHRiTLqL_lFvyea2v_mWFpapak',
    appId: '1:65493231963:ios:f9ade5aea727e62d7dd27e',
    messagingSenderId: '65493231963',
    projectId: 'oxyguard-f9e01',
    storageBucket: 'oxyguard-f9e01.appspot.com',
    iosBundleId: 'com.example.oxyGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt1s3yheYmmFPJ8BVW0lUEy4W6DhvKG0w',
    appId: '1:65493231963:web:e9d003535c8244157dd27e',
    messagingSenderId: '65493231963',
    projectId: 'oxyguard-f9e01',
    authDomain: 'oxyguard-f9e01.firebaseapp.com',
    storageBucket: 'oxyguard-f9e01.appspot.com',
    measurementId: 'G-MSC2LGEZWQ',
  );
}
